// build-app.mjs — Phase14.4: 운영 컴포넌트 26개 .jsx 를 빌드 시점에 JSX→JS 컴파일하여
//   하나의 클래식 스크립트 ../frontend/bundle/app.js 로 연결한다(런타임 babel 대체).
//
//   원칙:
//   - 변환만(transform), 번들링 아님 → 전역 스코프 공유 모델 보존(파일 간 bare 식별자 해소).
//     현재 babel-standalone 이 공유 스코프에서 무충돌 실행 = 최상위 이름 중복 없음 → concat 안전.
//   - jsxFactory=React.createElement (vendor-react 전역), import/export 미사용(전 파일 확인).
//   - 식별자 리네임 금지(minifyIdentifiers=false): 파일 간 참조가 최상위 이름에 의존.
//   - 산출물은 커밋(런타임 npm-free). index.html 은 이 1개 파일을 <script defer> 로 로드.
//     defer 라서 stom-ui.js(ESM 모듈, 문서순서상 head 에서 먼저 실행) 뒤에 실행 → window.fmt* 준비됨.

import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(__dirname, "../frontend");

// index.html 의 text/babel 로드 순서와 동일해야 한다(전역 정의 순서 보존).
const ORDER = [
  "connection.jsx", "panels.jsx", "run-compare.jsx", "engine.jsx", "chart.jsx",
  "hypothesis.jsx", "table.jsx", "cards.jsx", "code-viewer.jsx", "strategy-inspector.jsx",
  "phase-detail.jsx", "settings.jsx", "analysis.jsx", "research-pro.jsx", "research-lab.jsx",
  "research-wiki.jsx", "ai-context.jsx", "glossary.jsx", "backtest-charts.jsx", "backtest.jsx",
  "sim-live-chart.jsx", "simulation-charts.jsx", "simulation.jsx", "evolution-analysis.jsx",
  "dashboard-pages.jsx", "app.jsx",
];

const header =
  "/* GENERATED by webui-build/build-app.mjs (Phase14.4). DO NOT EDIT.\n" +
  "   운영 컴포넌트 .jsx 를 빌드 시점에 컴파일한 단일 클래식 스크립트(런타임 babel 대체).\n" +
  "   소스를 고치면 `npm run build` 로 재생성하라. 로드 순서는 build-app.mjs 의 ORDER. */\n";

const parts = [header];
for (const f of ORDER) {
  const code = readFileSync(resolve(FRONTEND, f), "utf8");
  const res = await esbuild.transform(code, {
    loader: "jsx",
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    // 변환만: 번들/포맷/리네임 없음. 공유 전역 스코프·파일간 참조 보존.
    minify: false,
    sourcemap: false,
  });
  parts.push(`\n;/* ==== ${f} ==== */\n${res.code}`);
}

const outPath = resolve(FRONTEND, "bundle/app.js");
writeFileSync(outPath, parts.join(""), "utf8");
console.log(`[build-app] wrote ${outPath} (${ORDER.length} files, ${parts.join("").length} bytes)`);
