// build-app.mjs — Phase14.4/14.5: 운영 컴포넌트 26개 .jsx 를 빌드 시점에 JSX→JS 컴파일하여
//   하나의 클래식 스크립트 ../frontend/bundle/app.js 로 연결하고(런타임 babel 대체),
//   산출물 content-hash 를 계산해 HTML 의 ?v= 캐시 버전을 자동 갱신한다(14.5 수동 핀 폐지).
//
//   원칙:
//   - 변환만(transform), 번들링 아님 → 전역 스코프 공유 모델 보존(파일 간 bare 식별자 해소).
//   - jsxFactory=React.createElement (vendor-react 전역), import/export 미사용(전 파일 확인).
//   - 식별자 리네임 금지(minifyIdentifiers=false): 파일 간 참조가 최상위 이름에 의존.
//   - 산출물(app.js·stom-ui.js)은 커밋(런타임 npm-free). ?v= 는 content-hash 라 수동 bump 불필요.
//     소스가 바뀌면 해시가 바뀌고 HTML 이 자동 갱신된다(재현성: 해시는 내용만의 함수, 타임스탬프 없음).

import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(__dirname, "../frontend");
const BUNDLE = resolve(FRONTEND, "bundle");

// index.html 의 로드 순서와 동일해야 한다(전역 정의 순서 보존).
const ORDER = [
  "connection.jsx", "panels.jsx", "run-compare.jsx", "engine.jsx", "chart.jsx",
  "hypothesis.jsx", "table.jsx", "cards.jsx", "code-viewer.jsx", "strategy-inspector.jsx",
  "phase-detail.jsx", "settings.jsx", "analysis.jsx", "research-pro.jsx", "research-lab.jsx",
  "research-wiki.jsx", "ai-context.jsx", "glossary.jsx", "backtest-charts.jsx", "backtest.jsx",
  "sim-live-chart.jsx", "simulation-charts.jsx", "simulation.jsx", "evolution-analysis.jsx",
  "dashboard-pages.jsx", "app.jsx",
];

// ---------- 1) app.js 컴파일·연결 ----------
const header =
  "/* GENERATED by webui-build/build-app.mjs (Phase14.4). DO NOT EDIT.\n" +
  "   운영 컴포넌트 .jsx 를 빌드 시점에 컴파일한 단일 클래식 스크립트(런타임 babel 대체).\n" +
  "   소스를 고치면 `npm run build` 로 재생성하라. 로드 순서는 build-app.mjs 의 ORDER. */\n";

const parts = [header];
for (const f of ORDER) {
  const code = readFileSync(resolve(FRONTEND, f), "utf8");
  const res = await esbuild.transform(code, {
    loader: "jsx",
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    minify: false,
    sourcemap: false,
  });
  parts.push(`\n;/* ==== ${f} ==== */\n${res.code}`);
}
const appPath = resolve(BUNDLE, "app.js");
writeFileSync(appPath, parts.join(""), "utf8");

// ---------- 2) content-hash 계산 ----------
const hash8 = (p) => createHash("sha256").update(readFileSync(p)).digest("hex").slice(0, 8);
const appV = hash8(appPath);
const stomPath = resolve(BUNDLE, "stom-ui.js");
const stomV = hash8(stomPath);  // stom-ui.js 는 선행 `vite build` 산출물.

// ---------- 3) HTML ?v= 자동 갱신(수동 핀 폐지) ----------
//   대상: bundle/app.js (index 만), bundle/stom-ui.js (번들을 로드하는 모든 엔트리).
const setV = (html, name, v) => {
  // src="bundle/NAME(?v=...)" 의 ?v= 만 정밀 교체. 파일명 "." 이스케이프(.map 오버매치 방지),
  // src 속성 앵커(주석·문서 내 파일명 언급은 건드리지 않음).
  const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return html.replace(
    new RegExp(`(src=["'])bundle/${esc}(\\?v=[^"']*)?(["'])`, "g"),
    `$1bundle/${name}?v=${v}$3`,
  );
};

const htmlTargets = ["index.html", "lab.html", "pro.html", "verdict.html", "STOM AI Dashboard.html"];
const touched = [];
for (const h of htmlTargets) {
  const p = resolve(FRONTEND, h);
  let s;
  try { s = readFileSync(p, "utf8"); } catch { continue; }
  let out = s;
  if (out.includes("bundle/app.js")) out = setV(out, "app.js", appV);
  if (out.includes("bundle/stom-ui.js")) out = setV(out, "stom-ui.js", stomV);
  if (out !== s) { writeFileSync(p, out, "utf8"); touched.push(h); }
}

// ---------- 4) 매니페스트(계약 검증용) ----------
const manifest = {
  note: "Phase14.5 build manifest — content-hash 캐시 버전(수동 ?v= 폐지). 빌드 산출.",
  bundles: { "app.js": { v: appV }, "stom-ui.js": { v: stomV } },
  appSources: ORDER,
};
writeFileSync(resolve(BUNDLE, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8");

console.log(`[build-app] app.js v=${appV} (${ORDER.length} files) · stom-ui.js v=${stomV}`);
console.log(`[build-app] html ?v= 갱신: ${touched.join(", ") || "(변경 없음)"}`);
